CREATE TABLE IF NOT EXISTS orders (id UUID PRIMARY KEY, channel TEXT NOT NULL, status TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS order_items (id BIGSERIAL PRIMARY KEY, order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE, name TEXT NOT NULL, quantity INTEGER NOT NULL CHECK (quantity > 0));
